---
abstract: 'A simple, extensible Perl debugger'
author:
  - 'Latest releases by Brock Wilcox, C<< <awwaiid@thelackthereof.org> >>'
  - 'Leon Brocard, C<< <acme@astray.com> >>'
build_requires:
  YAML: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-ebug
provides:
  DB::fake:
    file: lib/Devel/ebug/Backend.pm
    version: 0
  Devel::ebug:
    file: lib/Devel/ebug.pm
    version: 0.53_01
  Devel::ebug::Backend::Plugin::ActionPoints:
    file: lib/Devel/ebug/Backend/Plugin/ActionPoints.pm
    version: 0
  Devel::ebug::Backend::Plugin::Basic:
    file: lib/Devel/ebug/Backend/Plugin/Basic.pm
    version: 0
  Devel::ebug::Backend::Plugin::Codelines:
    file: lib/Devel/ebug/Backend/Plugin/Codelines.pm
    version: 0
  Devel::ebug::Backend::Plugin::Commands:
    file: lib/Devel/ebug/Backend/Plugin/Commands.pm
    version: 0
  Devel::ebug::Backend::Plugin::Eval:
    file: lib/Devel/ebug/Backend/Plugin/Eval.pm
    version: 0
  Devel::ebug::Backend::Plugin::Filenames:
    file: lib/Devel/ebug/Backend/Plugin/Filenames.pm
    version: 0
  Devel::ebug::Backend::Plugin::Output:
    file: lib/Devel/ebug/Backend/Plugin/Output.pm
    version: 0
  Devel::ebug::Backend::Plugin::Pad:
    file: lib/Devel/ebug/Backend/Plugin/Pad.pm
    version: 0
  Devel::ebug::Backend::Plugin::Ping:
    file: lib/Devel/ebug/Backend/Plugin/Ping.pm
    version: 0
  Devel::ebug::Backend::Plugin::Run:
    file: lib/Devel/ebug/Backend/Plugin/Run.pm
    version: 0
  Devel::ebug::Backend::Plugin::StackTrace:
    file: lib/Devel/ebug/Backend/Plugin/StackTrace.pm
    version: 0
  Devel::ebug::Console:
    file: lib/Devel/ebug/Console.pm
    version: 0
  Devel::ebug::Plugin::ActionPoints:
    file: lib/Devel/ebug/Plugin/ActionPoints.pm
    version: 0
  Devel::ebug::Plugin::Basic:
    file: lib/Devel/ebug/Plugin/Basic.pm
    version: 0
  Devel::ebug::Plugin::Codelines:
    file: lib/Devel/ebug/Plugin/Codelines.pm
    version: 0
  Devel::ebug::Plugin::Eval:
    file: lib/Devel/ebug/Plugin/Eval.pm
    version: 0
  Devel::ebug::Plugin::Filenames:
    file: lib/Devel/ebug/Plugin/Filenames.pm
    version: 0
  Devel::ebug::Plugin::Output:
    file: lib/Devel/ebug/Plugin/Output.pm
    version: 0
  Devel::ebug::Plugin::Pad:
    file: lib/Devel/ebug/Plugin/Pad.pm
    version: 0
  Devel::ebug::Plugin::Run:
    file: lib/Devel/ebug/Plugin/Run.pm
    version: 0
  Devel::ebug::Plugin::StackTrace:
    file: lib/Devel/ebug/Plugin/StackTrace.pm
    version: 0
requires:
  Carp: 0
  Class::Accessor::Chained::Fast: 0
  Devel::StackTrace: 0
  File::Find: 0
  IO::Socket::INET: 0
  Module::Pluggable: 0
  PadWalker: 0
  Proc::Background: 0
  Scalar::Util: 0
  String::Koremutake: 0
  Test::Expect: 0
  Test::More: 0
  YAML::Syck: 0.85
resources:
  license: http://dev.perl.org/licenses/
version: 0.53_01
